name: Build Apps (macOS Apple Silicon + Windows)

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  macos-arm64:
    name: macOS (Apple Silicon)
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            python -m pip install gooey wxPython==4.2.1 pandas numpy openpyxl xlsxwriter pdfplumber PyPDF2
          fi
          python -m pip install pyinstaller

      - name: Clean previous build dirs
        run: rm -rf build dist

      - name: Build app (.app)
        run: |
          pyinstaller --windowed --onefile --noconfirm --clean \
            --name "Off By Hour" \
            --collect-submodules gooey \
            --collect-submodules wx \
            --collect-data openpyxl \
            --collect-submodules xlsxwriter \
            --collect-submodules pdfplumber \
            --collect-submodules PyPDF2 \
            off_by_hour_gui_toggle.py
          ls -la dist

      - name: Zip macOS app
        run: |
          cd dist
          /usr/bin/zip -r "Off-By-Hour-macOS-arm64.zip" "Off By Hour.app"

      - name: Upload artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: Off-By-Hour-macOS-arm64
          path: dist/Off-By-Hour-macOS-arm64.zip

      - name: Upload to GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Off-By-Hour-macOS-arm64.zip

  windows:
    name: Windows (x64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        shell: powershell
        run: |
          python -m pip install --upgrade pip wheel setuptools
          if (Test-Path "requirements.txt") {
            python -m pip install -r requirements.txt
          } else {
            python -m pip install gooey wxPython==4.2.1 pandas numpy openpyxl xlsxwriter pdfplumber PyPDF2
          }
          python -m pip install pyinstaller

      - name: Clean previous build dirs
        shell: powershell
        run: |
          if (Test-Path "build") { Remove-Item -Recurse -Force "build" }
          if (Test-Path "dist")  { Remove-Item -Recurse -Force "dist" }

      - name: Build exe
        shell: powershell
        run: |
          pyinstaller --noconsole --onefile --noconfirm --clean --name "Off By Hour" `
            --collect-submodules gooey `
            --collect-submodules wx `
            --collect-data openpyxl `
            --collect-submodules xlsxwriter `
            --collect-submodules pdfplumber `
            --collect-submodules PyPDF2 `
            off_by_hour_gui_toggle.py
          Get-ChildItem dist

      - name: Zip Windows exe
        shell: powershell
        run: |
          Compress-Archive -Path "dist\Off By Hour.exe" -DestinationPath "dist\Off-By-Hour-Windows.zip" -Force

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: Off-By-Hour-Windows
          path: dist/Off-By-Hour-Windows.zip

      - name: Upload to GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Off-By-Hour-Windows.zip
